#!/usr/bin/python3
# [GLP3] Copyright (C) 2024  Michel Novus

# ----------- [inserta la raiz de localdoc en PYTHONPATH] -------------
import sys
import os
import os.path

localdoc_root = os.path.split(os.path.split(__file__)[0])[0]
sys.path.pop(0)
sys.path.insert(0, localdoc_root)
del localdoc_root
# ---------------------------------------------------------------------

import threading
import time

from default import CONFIG_FILEPATH
from configuration import load_configuration
from ipc import IpcServer


class KeepAlive(threading.Thread):
    """Mantiene el atributo 'status' en True hasta 'value' tiempo, lo cambia
    a False pasado el mismo y termina el Thread."""

    def __init__(self, value: float, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self._value = value
        self.status = True

    def run(self) -> None:
        time.sleep(self._value)
        self.status = False


def localdocd() -> int:
    with open(CONFIG_FILEPATH, "rt") as cfg_file:
        configuration = load_configuration(cfg_file.read())
        if not configuration.socket_filepath.startswith("/tmp/localdoc"):
            return 1
    ipc = IpcServer(configuration.socket_filepath)

    _keep_alive = KeepAlive(60)
    _keep_alive.start()
    while _keep_alive.status:
        response = ipc.wait_connection()
        if "localdocd_status" in response.keys():
            ipc.reply({"localdocd_status": "up"})
            continue
        ipc.reply({"response": "None"})
    ipc.close()
    return 0


if __name__ == "__main__":
    sys.exit(localdocd())
